import {plan,destination,formats} from './core.mjs';
const $=id=>document.getElementById(id), fields=['left','top','right','bottom'].map($);
let image=null,first=null,version=0,urls=[];
function box(){return fields.map(e=>e.value===''?NaN:Number(e.value)/100)}
function release(){urls.forEach(URL.revokeObjectURL);urls=[]}
function clear(){release();$('cards').replaceChildren()}
function say(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error)}
function source(){const c=$('source'),ctx=c.getContext('2d');c.width=image.width;c.height=image.height;ctx.drawImage(image,0,0);const [l,t,r,b]=box();if([l,t,r,b].every(Number.isFinite)&&r>l&&b>t){ctx.fillStyle='#10291e70';ctx.fillRect(0,0,c.width,t*c.height);ctx.fillRect(0,b*c.height,c.width,(1-b)*c.height);ctx.fillRect(0,t*c.height,l*c.width,(b-t)*c.height);ctx.fillRect(r*c.width,t*c.height,(1-r)*c.width,(b-t)*c.height);ctx.strokeStyle='#f8d895';ctx.lineWidth=Math.max(3,c.width/220);ctx.strokeRect(l*c.width,t*c.height,(r-l)*c.width,(b-t)*c.height)}if(first){ctx.fillStyle='#ffda79';ctx.beginPath();ctx.arc(first[0]*c.width,first[1]*c.height,c.width/100,0,Math.PI*2);ctx.fill()}}
function render(){if(!image)return;const generation=++version;clear();source();try{let pads=0;for(const f of formats){const p=plan(image.width,image.height,box(),f.w/f.h);if(p.mode==='pad')pads++;const card=document.createElement('article');card.className='card';const c=document.createElement('canvas');c.width=f.w;c.height=f.h;c.setAttribute('aria-label',f.name+'预览');const ctx=c.getContext('2d');ctx.fillStyle=$('color').value;ctx.fillRect(0,0,f.w,f.h);const d=destination(p,f.w,f.h);ctx.drawImage(image,p.x,p.y,p.w,p.h,d.x,d.y,d.w,d.h);const info=document.createElement('div'),h=document.createElement('h3');h.textContent=f.name;const tag=document.createElement('span');tag.className='tag'+(p.mode==='pad'?' pad':'');tag.textContent=p.mode==='pad'?'留白保全':'主体完整';const desc=document.createElement('p');desc.textContent=`${f.w} × ${f.h} · PNG`+(p.mode==='pad'?'\n保护框太宽或太高，保留整图。':'\n尽量保留原图上下文。');const a=document.createElement('a');a.className='download';a.textContent='正在生成…';c.toBlob(blob=>{if(generation!==version||!blob)return;const url=URL.createObjectURL(blob);urls.push(url);a.href=url;a.download=`留住-${f.w}x${f.h}.png`;a.textContent='下载 '+f.name;},'image/png');info.append(h,tag,desc,a);card.append(c,info);$('cards').append(card)}$('result-status').textContent=`3 个画幅已就绪 · ${pads} 个自动留白 · 保护框均完整保留`;$('result-status').className='';}catch(e){clear();$('result-status').textContent=e.message;$('result-status').className='error'}}
function setBox(values){fields.forEach((f,i)=>f.value=values[i]);first=null;$('selection').textContent='保护框已更新。再点两角可重新选择。';render()}
function load(img,label,values=[0,0,100,100]){image?.close?.();image=img;$('editor').hidden=false;say(`${label} · ${img.width} × ${img.height}，仅本地处理。`);setBox(values)}
$('sample').onclick=()=>{const c=document.createElement('canvas');c.width=1200;c.height=800;const x=c.getContext('2d');x.fillStyle='#dce5d4';x.fillRect(0,0,1200,800);x.fillStyle='#2b5343';x.fillRect(90,90,1020,620);x.fillStyle='#e9bd87';x.beginPath();x.arc(930,250,120,0,Math.PI*2);x.fill();x.fillStyle='#fff4dc';x.font='bold 88px sans-serif';x.fillText('周末 · 交换书集',160,390);x.font='32px sans-serif';x.fillText('带一本旧书，遇见一个新故事',165,465);x.font='25px sans-serif';x.fillText('SATURDAY  /  14:00—17:00',165,570);load(c,'内置示例',[12,34,88,74]);$('file').value=''};
$('file').onchange=async()=>{const file=$('file').files[0];if(!file)return;const token=++version;image?.close?.();image=null;first=null;clear();$('editor').hidden=true;$('result-status').textContent='等待有效图片。';if(!['image/jpeg','image/png','image/webp'].includes(file.type)){say('请选择 JPEG、PNG 或 WebP 图片。',true);return}if(file.size>15*1024*1024){say('图片超过15 MB，请先缩小文件。',true);return}say('正在读取本地图片…');try{const img=await createImageBitmap(file);if(token!==version){img.close();return}if(img.width*img.height>24000000){img.close();throw Error('图片超过2400万像素，请先缩小尺寸。')}load(img,file.name)}catch(e){if(token===version)say(e.message.startsWith('图片超过')?e.message:'无法读取这张图片，请换一个有效图片文件。',true)}};
$('source').onclick=e=>{if(!image)return;const rect=e.currentTarget.getBoundingClientRect();const p=[Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))];if(!first){first=p;$('selection').textContent='第一角已选，请点对角；结果仍为上一个完整保护框。';source()}else{const vals=[Math.min(first[0],p[0]),Math.min(first[1],p[1]),Math.max(first[0],p[0]),Math.max(first[1],p[1])].map((v,i)=>i<2?Math.floor(v*100):Math.ceil(v*100));setBox(vals)}};
fields.forEach(f=>f.oninput=()=>{first=null;$('selection').textContent='使用下方百分比调整保护框。';render()});$('whole').onclick=()=>setBox([0,0,100,100]);$('color').oninput=render;
